deliberate typo
After introducing this typo, with space before affiliation, I get the
obscure error:

make
./yaml-to-latex.py -i metadata.yaml -o metadata.tex
Traceback (most recent call last):
  File "./yaml-to-latex.py", line 93, in <module>
    content = generate_latex_metadata(filename_in, article)
  File "./yaml-to-latex.py", line 10, in generate_latex_metadata
    "% DO NOT EDIT - automatically generated from {filename}\n\n"
AttributeError: 'str' object has no attribute 'name'
make: *** [Makefile:18: metadata.tex] Error 1